# Generated by Django 4.1.2 on 2022-10-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('mensaje', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'contactModel',
                'verbose_name_plural': 'contactModels',
            },
        ),
    ]
